---
- hosts: mpi_nodes
  tasks:
  - name: install openmpi
    apt:
      name:
        - openmpi-bin
        - libopenmpi-dev
        - python3
        - python3-pip
      state: latest
      update_cache: true
    become: yes
    become_method: sudo

  - name: Install numpy and pytorch
    ansible.builtin.pip:
      name:
        - numpy
        - torch