---
- hosts: nfs_server
  become: yes
  tasks:
    - name: install nfs-kernel-server
      apt:
        name:
          - nfs-kernel-server
        state: latest
        update_cache: true
      become: yes
      become_method: sudo
    - name: Create a mountable directory if it does not exist
      file:
        path: /home/nfs
        state: directory
        owner: root
        group: root
        mode: '0775'
    - name: enable rpcbind nfs-server
      service:
        name: "{{ item }}"
        enabled: yes
      with_items:
        - rpcbind
        - nfs-server
    - name: Copy exports file.
      template:
        src: ./exports.j2
        dest: /etc/exports
        owner: root
        group: root
        mode: 0644
    - name: NFS apply change configrue
      shell: systemctl reload nfs;exportfs -a

- hosts: nfs_clients
  become: yes
  tasks:
    - name: install nfs-common
      apt:
        name:
          - nfs-common
        state: latest
        update_cache: true
      become: yes
      become_method: sudo
    - name: Create a mountable directory if it does not exist
      file:
        path: /home/{{ ansible_ssh_user }}
        state: directory
        owner: "{{ ansible_ssh_user }}"
        group: "{{ ansible_ssh_user }}"
        mode: '0775'
    - name: Ensure that nothing is currently mounted to target directory
      shell:
        cmd: umount /home/{{ ansible_ssh_user }}
      become: yes
      become_method: sudo
      ignore_errors: yes
    - name: Mount volume
      shell:
        cmd: mount {{ nfs_server }}:/home/{{ ansible_ssh_user }} /home/{{ ansible_ssh_user }}
      become: yes
      become_method: sudo